# Generated by Django 5.0.2 on 2024-02-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prazo_final',
            field=models.DateField(blank=True),
        ),
    ]
